# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9876f108dcd3aa05e7b9c9be955ebb93090a96bf942ccac22554ed6b5df5884d9902b0cafe1bb9de547c58d370b08619844888a749d84c830de0e8976e0b8290

test:
  secret_key_base: dce180422ca873613f4bc0a03c5441712adfd57c92cfb093f57a79bcfe4a6169ded3fd14e2cf6f848f563799db711ed49955217df21eea13274e76416ce9c34b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
